DCKS-77 install and run cs fixer after installing Laravel

diff --git a/ver b/ver
--- a/ver
+++ b/ver
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-VER_VERSION=1.0.1
+VER_VERSION=1.1.0
 
 if [ -f ./.env ]; then
     source ./.env
@@ -10,6 +10,7 @@ export APP_PORT=${APP_PORT:-80}
 export APP_SERVICE=${APP_SERVICE:-"app"}
 export HOST_UID
 export APP_SHORT_URL
+export DB_FORWARD_PORT=${DB_FORWARD_PORT:-3306}
 
 HOST_UID=$(id -u)
 
@@ -86,12 +87,40 @@ yarn () {
 }
 
 new () {
+    if [ -d "app" ]
+        then
+            echo "Laravel is already installed"
+            exit 1
+        fi
+
     docker run -u ${UID}:${UID} --rm -v $(pwd):/app -w /app composer composer create-project --prefer-dist laravel/laravel laravel-app
 
     shopt -s dotglob nullglob
 
     mv ./laravel-app/* .
     rm -rf laravel-app
+
+    sed -i 's/DB_HOST=127.0.0.1/DB_HOST=mysql/' .env .env.example
+    sed -i 's/DB_USERNAME=root/DB_USERNAME=db_user/' .env .env.example
+    sed -i 's/DB_PASSWORD=/DB_PASSWORD=db_secret/' .env .env.example
+
+    start
+
+    until curl localhost:"$DB_FORWARD_PORT" --http0.9 --output /dev/null --silent
+    do
+        {
+            echo 'Waiting for database to be ready...'
+            ((COUNT++)) && ((COUNT==20)) && echo "Could not connect to database after 20 tries!" && exit 1
+            sleep 3
+        } 1>&2
+    done
+
+    artisan migrate
+
+    lintInstall
+    lint
+
+    source .env && echo "$APP_URL"
 }
 
 hosts () {
@@ -118,6 +147,12 @@ lint () {
 }
 
 lintInstall () {
+    if [ -d "tools/php-cs-fixer" ]
+    then
+        echo "php-cs-fixer already installed"
+        exit 1
+    fi
+
     echo "Installing vertex-it/php-cs"
 
     mkdir --parents tools/php-cs-fixer
@@ -126,6 +161,9 @@ lintInstall () {
     cp tools/php-cs-fixer/vendor/vertex-it/php-cs/src/.php-cs-fixer.dist.php .php-cs-fixer.dist.php
 
     echo "Done. Run \"ver lint\" to run cs fixer"
+
+    grep -qxF '/tools' .gitignore || echo '/tools' >> .gitignore
+    grep -qxF '.php-cs-fixer.*' .gitignore || echo '.php-cs-fixer.*' >> .gitignore
 }
 
 version () {
